### ISSUE TITLE
When import qrng module I get ModuleNotFoundError

### ISSUE THREAD

**Issue by synco1111** [ozanerhansha/qRNG#6]
Hi,
I am trying to play a bit with the qRNG module based on the provided documentation, but from unknown reason I keep get the following error:
```python
import qrng

IBM_TOKEN = 1111*******
qrng.set_provider_as_IBMQ(IBM_TOKEN ) #empty string denotes local backend which can only use 'qasm_simulator'
qrng.set_backend('ibmq_london') #no args defaults to `qasm_simulator`
print(qrng.get_random_int32()) #generate a random 64 bit integer 10110319200202513540
rand_int = qrng.get_random_double(0,1) #generate a random 64 bit double between 0 to 1 0.9843570286395331
print(rand_int)
```
Once I try to run the script I get the following error:
```error
Exception has occurred: ModuleNotFoundError
No module named 'qiskit'
```

Any chance you familiar with that issue?
```
IDE: vscode - latest version 
Windows operation system
```

**Comment by Jiihwan-Kim** [comment]
Did you check whether qiskit is installed?
If it is not installed, please refer to the following:
[https://qiskit.org/documentation/getting_started.html](https://qiskit.org/documentation/getting_started.html)
